apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    basicAuth: true
    basicAuthUser: admin
    basicAuthPassword: ${GRAFANA_PROM_PASSWORD}

