apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: archon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: archon/frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: archon-config
              key: API_URL
