auth_enabled: false
server:
  http_listen_port: 3100
storage_config:
  filesystem:
    directory: ${LOKI_STORAGE_DIR}
chunk_store_config:
  max_look_back_period: 0s
schema_config:
  configs:
    - from: 2020-10-15
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h


