apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "archon-mcp.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "archon-mcp.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "archon-mcp.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecret.name }}
                  key: {{ .Values.envSecret.key }}

